language: python
python:
- '3.5'
- '3.6'
- '3.7'
install:
- sudo apt-get update
- python --version
- which python

- pip install Cython contextlib2 pillow lxml jupyter matplotlib

- git clone https://github.com/tensorflow/models.git
- cd models/research
- ls
- wget -O protobuf.zip https://github.com/google/protobuf/releases/download/v3.0.0/protoc-3.0.0-linux-x86_64.zip && unzip protobuf.zip
- ./bin/protoc object_detection/protos/*.proto --python_out=.
- export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
- cd ../..

- pip install .[tf-cpu,testing]
script: make tests
after_success:
- coveralls
git:
  depth: 3
env:
  global:
    secure: byc2wWgxM4rrewNYwvJymK0TQOwqxufcHtv2u82fJ9lHZMtduztOlRemFQyRTzC6iqgQucVZtYu0E1+GWnzdwRZKQ2mvMNcMhcaaoNN9CjIjkjauFFJKGgwKRvUc4SeopDsDN7eVBai3L/gmghlYkKY192HS7uKemwW0TD17WwWCxBqYMI3X9BpxqYxXKxMTRLwI838dvfo7Ab8LHsdPPEcfH5wq2Z6NW6iMIWYFEKzCwt08NFfTXfb3zLar2jKntFN/H2Zn4x/JswKeFFcvyxJud4MrHOt6ckyuVKd07M6RjROC50CwCMfIe7ZC1BWmqZyE/ib+xCz3ATJ4Bv1omiH5aIexPrvi6RE33WGguDWWg1/lbsvZWOM+SG+nStBmiUT+lT7Ap/o/a1X7u4hdRAmkh6sXUUji/0TL0kjDoKa7J4p8BqoWxbyeDgAWu+EB8CjhL+8toSPV7/FhxSlMV9RncyfK1Aix1iJ9JSZ+PNli/1q0Do29Tbt3dKO2N+9wvdlADwbzpm/WlOLgY58y81NVQUZMwp3+L55cnvVe7XnjV72PnV7n1k1oJ9PoAnvWVQaY5TAPEmd3NDUeaqgIhlF6IXtF1lrJUXXibPQ3HW47BSwskpwnaMNmG7IOBQjj+B3B+qDUIyndSGDcauNmg69gNK8DdrfzA8OWkvlvRcQ=
